### ISSUE TITLE
EXIT WITH ERROR

### ISSUE THREAD

**Issue by moleoxa** [rolandas-rimkus/FancyZones#1]
Just Like A Programmer who learn to code for the first day.
Without any Exception Catch Operation.。。。

**Comment by rolandas-rimkus** [comment]
More information on what you ran and what failed would be helpful. Complaining without being constructive is not good for anyone. Also a new release was pushed out today https://github.com/rolandas-rimkus/FancyZones/releases/tag/0.76.2.2 that might have fixed some issues you were having. Even if I don't know the full details.

**Comment by moleoxa** [comment]
> More information on what you ran and what failed would be helpful. Complaining without being constructive is not good for anyone. Also a new release was pushed out today https://github.com/rolandas-rimkus/FancyZones/releases/tag/0.76.2.2 that might have fixed some issues you were having. Even if I don't know the full details.

That what just I mean.... Your script is telling what to do. But,,, IF any command did not run until success, it would exit powershell and did not leave the time for user to see which command is fail and why is fail.

For exmaple, if the script exit because of the network (Download Task could not been completed) at first running.
The seconnd time you running that script,,, it would exit directly because the command "System Call: Create a folder name 'temp'." is refused.
_____________________________________________

I just never saw there had been a release yesterday, I will try it.

**Comment by rolandas-rimkus** [comment]
Okay this makes sense now. The new release will not help with edge cases when specific commands fail. So will have to deploy a new release at some point this week when I have some free time. I did not bother with exception handling as I did not want to over complicate and bloat the initial logic.

**Comment by rolandas-rimkus** [comment]
Deployed new release: https://github.com/rolandas-rimkus/FancyZones/releases/tag/0.77.0.1 that adds checks so it should be easier to rerun the deployment if one of the steps fail.
